[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@oz=/lib/openzeppelin-contracts/contracts/'
]
solc_version = "0.8.17"

[fuzz]
runs = 1


[invariant]
runs = 1000
